### ISSUE TITLE
Another approach

### ISSUE THREAD

**Issue by espr14** [SnakeOilXY/ProosaXY#1]
Hello. I was also trying to convert Prusa i3 MK3 to coreXY. Maybe you can be inspired by my approach and take some printed parts. The main difference is use of one extra ALU frame and no extra ALU profiles. The frame is much more rigid and has very low skew compared to bolted ALU profiles. Also the power supply holds the frame. Unfortunatelly, I haven't finished the Z axis.

https://www.printables.com/model/72811-prusa-i3-mk3-corexy-3d-printer

**Comment by espr14** [comment]
If you'll be modding Prusa MINI I can help (also with FW).

**Comment by ChipCE** [comment]
Hi, that look nice!
About the mini, I'm not sure if the cost is still in resonable range. Build the tic-tac from scratch might be a better option. 
https://www.printables.com/model/164038-tic-tac-miniaturised-v-minion

About the fw, what fw are you familiar with?

**Comment by espr14** [comment]
I thought about MINI in the box with double Z. This would be cheaper than Voron 0.2, still.

I'm maintainer of Snake FW (previously Llama FW) based on Buddy FW for MINI, MK4 and XL. I did some changes in MK3 FW but I don't have the printer any more.
https://github.com/Snake-FW/P32-FW

**Comment by ChipCE** [comment]
> I thought about MINI in the box with double Z. This would be cheaper than Voron 0.2, still.

i did this back then with a scaled down bear frame and custom bowden bear-extruder. It can run at 250% speed of the mk3 without a sweat. 

https://photos.app.goo.gl/DhzNpycHasufgsmX9

> I'm maintainer of Snake FW (previously Llama FW) based on Buddy FW for MINI, MK4 and XL. I did some changes in MK3 FW but I don't have the printer any more.

Great, I would love to have you join the team and help us with Marlin fw. 
I made the TH3D online compiler few years ago, but have to re-flash firmware each change is far over my patience.

**Comment by espr14** [comment]
Nice. But I'd like enclosed printer more than the max. speed. I don't like the X axis motor being out of the box in the i3 printers. In my custom 3D printer I've put X motor between the Y rods like in Chaos MK3 Box (https://www.printables.com/model/103675-prusa-box-mk3s-chaos-edition-chaosbox/collections).

I can help with the FW. But I don't have the Prusa i3 MK3 board you're using.
