### ISSUE TITLE
Prusa bear frame corexy

### ISSUE THREAD

**Issue by SupernovaIndustries** [SnakeOilXY/ProosaXY#2]
Fantastic work! I always wanted to transform my prusa into a corexy but ,while waiting to have time and money, I changed the standard frame with the bear one.
Do you think that, with some modifications, I can reuse the bear frame?

**Comment by ChipCE** [comment]
You can re-use some but not all parts of the bear frame. We are testing the frame kit for this build. I think the price will be affordable enough.
