### ISSUE TITLE
Some Questions

### ISSUE THREAD

**Issue by 3DCoded** [SnakeOilXY/ProosaXY#4]
I am looking into building this for my Prusa MK3S+, but I have a few questions first:
This is (will be) a custom-built Prusa MK3S+ made from the frame left over after I did the Bear Upgrade. My only significant changes were using 0.9º steppers on x and y (high torque on y) and making a custom dual extruder head. 

- What parts need to be removed/modified from the original Prusa to do this upgrade (so I don't buy them)?
- Where do you buy your aluminum extrusions and DIN rails (I couldn't find the right lengths on Amazon or Alieexpress)?
- What's the status of the build instructions? I don't think I'll be able to build this without them, as this will be my first time messing with CoreXY.

**Comment by ChipCE** [comment]
> I am looking into building this for my Prusa MK3S+, but I have a few questions first: This is a custom-built Prusa MK3S+ made from the frame left over after I did the Bear Upgrade. My only significant changes were using 0.9º steppers on x and y (high torque on y) and making a custom dual extruder head.
> 
I have the same 0.9º  E3D high torque motor on mine too. They are work great up to about 300mm/s.
>     * What parts need to be removed/modified from the original Prusa to do this upgrade (so I don't buy them)?
> 
The list available on our [google doc BOM list](https://docs.google.com/spreadsheets/d/1j1bnA8rNjDqpTVEdiqrsRlNeggI6PYRAoSBm1F8bvCs/edit)


>     * Where do you buy your aluminum extrusions and DIN rails (I couldn't find the right lengths on Amazon or Alieexpress)?
> 

Bought mine from Misumi. You can get our open-beta kit from [Fabreeko](https://www.fabreeko.com/products/proosa-xy-conversion-for-mk3s-to-core-xy-by-snakeoilxy-open-beta). It have most of the parts you will need. 

>     * What's the status of the build instructions? I don't think I'll be able to build this without them, as this will be my first time messing with CoreXY.
We only have a simple build log, and some live build videos on our [youtube channel](https://www.youtube.com/channel/UCIwlxzAJvDTgEfAodtsRMdw) now. 

If you want faster response, please visit our discord server.
