### ISSUE TITLE
State of the project

### ISSUE THREAD

**Issue by Dzarda7** [SnakeOilXY/ProosaXY#6]
Hi @ChipCE may I ask what is the current state of the project? I am in the process of building it and want to know, if there is something I should know. Do you have some newer revesion etc.? Also, can I use old head instead of new one? Thank you so much for this awesome project.

**Comment by ChipCE** [comment]
@Dzarda7 except the optional tophat, the design if completed. We already have many builds with good result. 
The files on git hib are the newest. 
Please visit our discord if you have some other option. I think other members already build the machine can help with question about hardwares that not official supported atm.

**Comment by Dzarda7** [comment]
Thank you for quick reply.
